/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring-app
 * OpenAPI spec version: 0.1.0
 */
import type { BulkLineUpdateStages } from './bulkLineUpdateStages';

/**
 * Apply the same stage changes to multiple lines at once.
 */
export interface BulkLineUpdate {
  line_ids: string[];
  stages: BulkLineUpdateStages;
}
