/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring
 * OpenAPI spec version: 0.1.0
 */
import type { ComponentDetailCatalogKey } from './componentDetailCatalogKey';
import type { ComponentDetailValueDB } from './componentDetailValueDB';
import type { ComponentDetailGainDB } from './componentDetailGainDB';
import type { ComponentDetailFilterType } from './componentDetailFilterType';
import type { ComponentDetailAmplifierType } from './componentDetailAmplifierType';

export interface ComponentDetail {
  type: string;
  manufacturer?: string;
  model: string;
  catalog_key?: ComponentDetailCatalogKey;
  serial?: string;
  value_dB?: ComponentDetailValueDB;
  gain_dB?: ComponentDetailGainDB;
  filter_type?: ComponentDetailFilterType;
  amplifier_type?: ComponentDetailAmplifierType;
}
