/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring
 * OpenAPI spec version: 0.1.0
 */
import type { ChipInfo } from './chipInfo';

export type CooldownDetailChip = ChipInfo | null;
