/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring
 * OpenAPI spec version: 0.1.0
 */

export interface CooldownMeta {
  cooldown_id: string;
  date: string;
  cryo?: string;
  operator?: string;
  purpose?: string;
  notes?: string;
}
