/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryowire-app
 * OpenAPI spec version: 0.1.0
 */
import type { CooldownMeta } from './cooldownMeta';
import type { CooldownDetailChip } from './cooldownDetailChip';
import type { SummarySection } from './summarySection';

export interface CooldownDetail {
  metadata: CooldownMeta;
  chip?: CooldownDetailChip;
  summary: SummarySection[];
}
