/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryowire-app
 * OpenAPI spec version: 0.1.0
 */
import type { CreateResponseSync } from './createResponseSync';

export interface CreateResponse {
  status: string;
  path: string;
  sync?: CreateResponseSync;
}
