/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryowire-app
 * OpenAPI spec version: 0.1.0
 */
import type { YearGroup } from './yearGroup';

export interface CryoEntry {
  name: string;
  years: YearGroup[];
}
