/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring
 * OpenAPI spec version: 0.1.0
 */
import type { LineUpdateStages } from './lineUpdateStages';

export interface LineUpdate {
  stages: LineUpdateStages;
}
