/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryowire-app
 * OpenAPI spec version: 0.1.0
 */
import type { LineDetail } from './lineDetail';

export interface LinesResponse {
  control: LineDetail[];
  readout_send: LineDetail[];
  readout_return: LineDetail[];
}
