/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring-app
 * OpenAPI spec version: 0.1.0
 */
import type { MetadataUpdateOperator } from './metadataUpdateOperator';
import type { MetadataUpdatePurpose } from './metadataUpdatePurpose';
import type { MetadataUpdateNotes } from './metadataUpdateNotes';

export interface MetadataUpdate {
  operator?: MetadataUpdateOperator;
  purpose?: MetadataUpdatePurpose;
  notes?: MetadataUpdateNotes;
}
