/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryowire-app
 * OpenAPI spec version: 0.1.0
 */
import type { ModuleStage } from './moduleStage';

export interface ModuleTemplate {
  name: string;
  file: string;
  line_type: string;
  stages: ModuleStage[];
}
