/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring-app
 * OpenAPI spec version: 0.1.0
 */
import type { NewCooldownRequestCooldownDate } from './newCooldownRequestCooldownDate';

export interface NewCooldownRequest {
  cryo: string;
  chip_name: string;
  num_qubits: number;
  cooldown_date?: NewCooldownRequestCooldownDate;
  operator?: string;
  purpose?: string;
}
