/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring-app
 * OpenAPI spec version: 0.1.0
 */
import type { NewCooldownForCryoRequestCooldownDate } from './newCooldownForCryoRequestCooldownDate';

export interface NewCooldownForCryoRequest {
  cooldown_id?: string;
  cooldown_date?: NewCooldownForCryoRequestCooldownDate;
  operator?: string;
  purpose?: string;
}
