/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring-app
 * OpenAPI spec version: 0.1.0
 */
import type { RepoInfoRemoteUrl } from './repoInfoRemoteUrl';

export interface RepoInfo {
  remote_url: RepoInfoRemoteUrl;
  local_path: string;
  has_git: boolean;
  ready: boolean;
}
