/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring-app
 * OpenAPI spec version: 0.1.0
 */
import type { SyncResult } from './syncResult';

export type StatusResponseSync = SyncResult | null;
