/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryowire-app
 * OpenAPI spec version: 0.1.0
 */
import type { SummaryLine } from './summaryLine';

export interface SummarySection {
  label: string;
  lines: SummaryLine[];
}
