/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryowire-app
 * OpenAPI spec version: 0.1.0
 */
import type { SummaryLineStages } from './summaryLineStages';

export interface SummaryLine {
  line_id: string;
  qubits: string;
  total_atten: number;
  total_gain: number;
  stages: SummaryLineStages;
}
