/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring-app
 * OpenAPI spec version: 0.1.0
 */

export interface SyncResult {
  committed?: boolean;
  pushed?: boolean;
  push_error?: string;
  has_unpushed?: boolean;
}
