/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring-app
 * OpenAPI spec version: 0.1.0
 */

export interface SyncInfo {
  has_git: boolean;
  has_remote: boolean;
  unpushed_commits: number;
  branch: string;
}
