/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryowire-app
 * OpenAPI spec version: 0.1.0
 */
import type {
  BulkLineUpdate,
  CooldownDetail,
  CreateResponse,
  CryoEntry,
  HTTPValidationError,
  LineUpdate,
  LinesResponse,
  MetadataUpdate,
  NewCooldownForCryoRequest,
  NewCooldownRequest,
  RepoInfo,
  RepoSetupRequest,
  StatusResponse,
  SyncInfo,
  TemplateUpdate,
  TemplatesInfo
} from '../../models';

import { customFetch } from '../../fetcher';

/**
 * @summary Get Repo Info
 */
export type getRepoInfoApiRepoGetResponse200 = {
  data: RepoInfo
  status: 200
}
    
export type getRepoInfoApiRepoGetResponseSuccess = (getRepoInfoApiRepoGetResponse200) & {
  headers: Headers;
};
;

export type getRepoInfoApiRepoGetResponse = (getRepoInfoApiRepoGetResponseSuccess)

export const getGetRepoInfoApiRepoGetUrl = () => {


  

  return `/api/repo`
}

export const getRepoInfoApiRepoGet = async ( options?: RequestInit): Promise<getRepoInfoApiRepoGetResponse> => {
  
  return customFetch<getRepoInfoApiRepoGetResponse>(getGetRepoInfoApiRepoGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Setup Repo
 */
export type setupRepoApiRepoSetupPostResponse200 = {
  data: RepoInfo
  status: 200
}

export type setupRepoApiRepoSetupPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type setupRepoApiRepoSetupPostResponseSuccess = (setupRepoApiRepoSetupPostResponse200) & {
  headers: Headers;
};
export type setupRepoApiRepoSetupPostResponseError = (setupRepoApiRepoSetupPostResponse422) & {
  headers: Headers;
};

export type setupRepoApiRepoSetupPostResponse = (setupRepoApiRepoSetupPostResponseSuccess | setupRepoApiRepoSetupPostResponseError)

export const getSetupRepoApiRepoSetupPostUrl = () => {


  

  return `/api/repo/setup`
}

export const setupRepoApiRepoSetupPost = async (repoSetupRequest: RepoSetupRequest, options?: RequestInit): Promise<setupRepoApiRepoSetupPostResponse> => {
  
  return customFetch<setupRepoApiRepoSetupPostResponse>(getSetupRepoApiRepoSetupPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      repoSetupRequest,)
  }
);}


/**
 * @summary Pull Repo
 */
export type pullRepoApiRepoPullPostResponse200 = {
  data: StatusResponse
  status: 200
}
    
export type pullRepoApiRepoPullPostResponseSuccess = (pullRepoApiRepoPullPostResponse200) & {
  headers: Headers;
};
;

export type pullRepoApiRepoPullPostResponse = (pullRepoApiRepoPullPostResponseSuccess)

export const getPullRepoApiRepoPullPostUrl = () => {


  

  return `/api/repo/pull`
}

export const pullRepoApiRepoPullPost = async ( options?: RequestInit): Promise<pullRepoApiRepoPullPostResponse> => {
  
  return customFetch<pullRepoApiRepoPullPostResponse>(getPullRepoApiRepoPullPostUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Get Sync Info
 */
export type getSyncInfoApiRepoSyncGetResponse200 = {
  data: SyncInfo
  status: 200
}
    
export type getSyncInfoApiRepoSyncGetResponseSuccess = (getSyncInfoApiRepoSyncGetResponse200) & {
  headers: Headers;
};
;

export type getSyncInfoApiRepoSyncGetResponse = (getSyncInfoApiRepoSyncGetResponseSuccess)

export const getGetSyncInfoApiRepoSyncGetUrl = () => {


  

  return `/api/repo/sync`
}

export const getSyncInfoApiRepoSyncGet = async ( options?: RequestInit): Promise<getSyncInfoApiRepoSyncGetResponse> => {
  
  return customFetch<getSyncInfoApiRepoSyncGetResponse>(getGetSyncInfoApiRepoSyncGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary List Cryos
 */
export type listCryosApiCryosGetResponse200 = {
  data: CryoEntry[]
  status: 200
}
    
export type listCryosApiCryosGetResponseSuccess = (listCryosApiCryosGetResponse200) & {
  headers: Headers;
};
;

export type listCryosApiCryosGetResponse = (listCryosApiCryosGetResponseSuccess)

export const getListCryosApiCryosGetUrl = () => {


  

  return `/api/cryos`
}

export const listCryosApiCryosGet = async ( options?: RequestInit): Promise<listCryosApiCryosGetResponse> => {
  
  return customFetch<listCryosApiCryosGetResponse>(getListCryosApiCryosGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Return the raw cooldown.yaml bundle as JSON.
 * @summary Get Cooldown Bundle
 */
export type getCooldownBundleApiCryosCryoYearCooldownBundleGetResponse200 = {
  data: unknown
  status: 200
}

export type getCooldownBundleApiCryosCryoYearCooldownBundleGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getCooldownBundleApiCryosCryoYearCooldownBundleGetResponseSuccess = (getCooldownBundleApiCryosCryoYearCooldownBundleGetResponse200) & {
  headers: Headers;
};
export type getCooldownBundleApiCryosCryoYearCooldownBundleGetResponseError = (getCooldownBundleApiCryosCryoYearCooldownBundleGetResponse422) & {
  headers: Headers;
};

export type getCooldownBundleApiCryosCryoYearCooldownBundleGetResponse = (getCooldownBundleApiCryosCryoYearCooldownBundleGetResponseSuccess | getCooldownBundleApiCryosCryoYearCooldownBundleGetResponseError)

export const getGetCooldownBundleApiCryosCryoYearCooldownBundleGetUrl = (cryo: string,
    year: string,
    cooldown: string,) => {


  

  return `/api/cryos/${cryo}/${year}/${cooldown}/bundle`
}

export const getCooldownBundleApiCryosCryoYearCooldownBundleGet = async (cryo: string,
    year: string,
    cooldown: string, options?: RequestInit): Promise<getCooldownBundleApiCryosCryoYearCooldownBundleGetResponse> => {
  
  return customFetch<getCooldownBundleApiCryosCryoYearCooldownBundleGetResponse>(getGetCooldownBundleApiCryosCryoYearCooldownBundleGetUrl(cryo,year,cooldown),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get Cooldown
 */
export type getCooldownApiCryosCryoYearCooldownGetResponse200 = {
  data: CooldownDetail
  status: 200
}

export type getCooldownApiCryosCryoYearCooldownGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getCooldownApiCryosCryoYearCooldownGetResponseSuccess = (getCooldownApiCryosCryoYearCooldownGetResponse200) & {
  headers: Headers;
};
export type getCooldownApiCryosCryoYearCooldownGetResponseError = (getCooldownApiCryosCryoYearCooldownGetResponse422) & {
  headers: Headers;
};

export type getCooldownApiCryosCryoYearCooldownGetResponse = (getCooldownApiCryosCryoYearCooldownGetResponseSuccess | getCooldownApiCryosCryoYearCooldownGetResponseError)

export const getGetCooldownApiCryosCryoYearCooldownGetUrl = (cryo: string,
    year: string,
    cooldown: string,) => {


  

  return `/api/cryos/${cryo}/${year}/${cooldown}`
}

export const getCooldownApiCryosCryoYearCooldownGet = async (cryo: string,
    year: string,
    cooldown: string, options?: RequestInit): Promise<getCooldownApiCryosCryoYearCooldownGetResponse> => {
  
  return customFetch<getCooldownApiCryosCryoYearCooldownGetResponse>(getGetCooldownApiCryosCryoYearCooldownGetUrl(cryo,year,cooldown),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get Diagram
 */
export type getDiagramApiCryosCryoYearCooldownDiagramGetResponse200 = {
  data: unknown
  status: 200
}

export type getDiagramApiCryosCryoYearCooldownDiagramGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getDiagramApiCryosCryoYearCooldownDiagramGetResponseSuccess = (getDiagramApiCryosCryoYearCooldownDiagramGetResponse200) & {
  headers: Headers;
};
export type getDiagramApiCryosCryoYearCooldownDiagramGetResponseError = (getDiagramApiCryosCryoYearCooldownDiagramGetResponse422) & {
  headers: Headers;
};

export type getDiagramApiCryosCryoYearCooldownDiagramGetResponse = (getDiagramApiCryosCryoYearCooldownDiagramGetResponseSuccess | getDiagramApiCryosCryoYearCooldownDiagramGetResponseError)

export const getGetDiagramApiCryosCryoYearCooldownDiagramGetUrl = (cryo: string,
    year: string,
    cooldown: string,) => {


  

  return `/api/cryos/${cryo}/${year}/${cooldown}/diagram`
}

export const getDiagramApiCryosCryoYearCooldownDiagramGet = async (cryo: string,
    year: string,
    cooldown: string, options?: RequestInit): Promise<getDiagramApiCryosCryoYearCooldownDiagramGetResponse> => {
  
  return customFetch<getDiagramApiCryosCryoYearCooldownDiagramGetResponse>(getGetDiagramApiCryosCryoYearCooldownDiagramGetUrl(cryo,year,cooldown),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get Diagram Full
 */
export type getDiagramFullApiCryosCryoYearCooldownDiagramFullGetResponse200 = {
  data: unknown
  status: 200
}

export type getDiagramFullApiCryosCryoYearCooldownDiagramFullGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getDiagramFullApiCryosCryoYearCooldownDiagramFullGetResponseSuccess = (getDiagramFullApiCryosCryoYearCooldownDiagramFullGetResponse200) & {
  headers: Headers;
};
export type getDiagramFullApiCryosCryoYearCooldownDiagramFullGetResponseError = (getDiagramFullApiCryosCryoYearCooldownDiagramFullGetResponse422) & {
  headers: Headers;
};

export type getDiagramFullApiCryosCryoYearCooldownDiagramFullGetResponse = (getDiagramFullApiCryosCryoYearCooldownDiagramFullGetResponseSuccess | getDiagramFullApiCryosCryoYearCooldownDiagramFullGetResponseError)

export const getGetDiagramFullApiCryosCryoYearCooldownDiagramFullGetUrl = (cryo: string,
    year: string,
    cooldown: string,) => {


  

  return `/api/cryos/${cryo}/${year}/${cooldown}/diagram/full`
}

export const getDiagramFullApiCryosCryoYearCooldownDiagramFullGet = async (cryo: string,
    year: string,
    cooldown: string, options?: RequestInit): Promise<getDiagramFullApiCryosCryoYearCooldownDiagramFullGetResponse> => {
  
  return customFetch<getDiagramFullApiCryosCryoYearCooldownDiagramFullGetResponse>(getGetDiagramFullApiCryosCryoYearCooldownDiagramFullGetUrl(cryo,year,cooldown),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get Components
 */
export type getComponentsApiComponentsGetResponse200 = {
  data: unknown
  status: 200
}
    
export type getComponentsApiComponentsGetResponseSuccess = (getComponentsApiComponentsGetResponse200) & {
  headers: Headers;
};
;

export type getComponentsApiComponentsGetResponse = (getComponentsApiComponentsGetResponseSuccess)

export const getGetComponentsApiComponentsGetUrl = () => {


  

  return `/api/components`
}

export const getComponentsApiComponentsGet = async ( options?: RequestInit): Promise<getComponentsApiComponentsGetResponse> => {
  
  return customFetch<getComponentsApiComponentsGetResponse>(getGetComponentsApiComponentsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get Templates
 */
export type getTemplatesApiTemplatesGetResponse200 = {
  data: TemplatesInfo
  status: 200
}
    
export type getTemplatesApiTemplatesGetResponseSuccess = (getTemplatesApiTemplatesGetResponse200) & {
  headers: Headers;
};
;

export type getTemplatesApiTemplatesGetResponse = (getTemplatesApiTemplatesGetResponseSuccess)

export const getGetTemplatesApiTemplatesGetUrl = () => {


  

  return `/api/templates`
}

export const getTemplatesApiTemplatesGet = async ( options?: RequestInit): Promise<getTemplatesApiTemplatesGetResponse> => {
  
  return customFetch<getTemplatesApiTemplatesGetResponse>(getGetTemplatesApiTemplatesGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Update Template
 */
export type updateTemplateApiTemplatesFilenamePutResponse200 = {
  data: StatusResponse
  status: 200
}

export type updateTemplateApiTemplatesFilenamePutResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateTemplateApiTemplatesFilenamePutResponseSuccess = (updateTemplateApiTemplatesFilenamePutResponse200) & {
  headers: Headers;
};
export type updateTemplateApiTemplatesFilenamePutResponseError = (updateTemplateApiTemplatesFilenamePutResponse422) & {
  headers: Headers;
};

export type updateTemplateApiTemplatesFilenamePutResponse = (updateTemplateApiTemplatesFilenamePutResponseSuccess | updateTemplateApiTemplatesFilenamePutResponseError)

export const getUpdateTemplateApiTemplatesFilenamePutUrl = (filename: string,) => {


  

  return `/api/templates/${filename}`
}

export const updateTemplateApiTemplatesFilenamePut = async (filename: string,
    templateUpdate: TemplateUpdate, options?: RequestInit): Promise<updateTemplateApiTemplatesFilenamePutResponse> => {
  
  return customFetch<updateTemplateApiTemplatesFilenamePutResponse>(getUpdateTemplateApiTemplatesFilenamePutUrl(filename),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      templateUpdate,)
  }
);}


/**
 * @summary Get Lines
 */
export type getLinesApiCryosCryoYearCooldownLinesGetResponse200 = {
  data: LinesResponse
  status: 200
}

export type getLinesApiCryosCryoYearCooldownLinesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getLinesApiCryosCryoYearCooldownLinesGetResponseSuccess = (getLinesApiCryosCryoYearCooldownLinesGetResponse200) & {
  headers: Headers;
};
export type getLinesApiCryosCryoYearCooldownLinesGetResponseError = (getLinesApiCryosCryoYearCooldownLinesGetResponse422) & {
  headers: Headers;
};

export type getLinesApiCryosCryoYearCooldownLinesGetResponse = (getLinesApiCryosCryoYearCooldownLinesGetResponseSuccess | getLinesApiCryosCryoYearCooldownLinesGetResponseError)

export const getGetLinesApiCryosCryoYearCooldownLinesGetUrl = (cryo: string,
    year: string,
    cooldown: string,) => {


  

  return `/api/cryos/${cryo}/${year}/${cooldown}/lines`
}

export const getLinesApiCryosCryoYearCooldownLinesGet = async (cryo: string,
    year: string,
    cooldown: string, options?: RequestInit): Promise<getLinesApiCryosCryoYearCooldownLinesGetResponse> => {
  
  return customFetch<getLinesApiCryosCryoYearCooldownLinesGetResponse>(getGetLinesApiCryosCryoYearCooldownLinesGetUrl(cryo,year,cooldown),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Update Line
 */
export type updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutResponse200 = {
  data: StatusResponse
  status: 200
}

export type updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutResponseSuccess = (updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutResponse200) & {
  headers: Headers;
};
export type updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutResponseError = (updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutResponse422) & {
  headers: Headers;
};

export type updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutResponse = (updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutResponseSuccess | updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutResponseError)

export const getUpdateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutUrl = (cryo: string,
    year: string,
    cooldown: string,
    fileType: string,
    lineId: string,) => {


  

  return `/api/cryos/${cryo}/${year}/${cooldown}/lines/${fileType}/${lineId}`
}

export const updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPut = async (cryo: string,
    year: string,
    cooldown: string,
    fileType: string,
    lineId: string,
    lineUpdate: LineUpdate, options?: RequestInit): Promise<updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutResponse> => {
  
  return customFetch<updateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutResponse>(getUpdateLineApiCryosCryoYearCooldownLinesFileTypeLineIdPutUrl(cryo,year,cooldown,fileType,lineId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lineUpdate,)
  }
);}


/**
 * Apply the same stage configuration to multiple lines at once.
 * @summary Bulk Update Lines
 */
export type bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutResponse200 = {
  data: StatusResponse
  status: 200
}

export type bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutResponseSuccess = (bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutResponse200) & {
  headers: Headers;
};
export type bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutResponseError = (bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutResponse422) & {
  headers: Headers;
};

export type bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutResponse = (bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutResponseSuccess | bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutResponseError)

export const getBulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutUrl = (cryo: string,
    year: string,
    cooldown: string,
    fileType: string,) => {


  

  return `/api/cryos/${cryo}/${year}/${cooldown}/lines/${fileType}`
}

export const bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePut = async (cryo: string,
    year: string,
    cooldown: string,
    fileType: string,
    bulkLineUpdate: BulkLineUpdate, options?: RequestInit): Promise<bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutResponse> => {
  
  return customFetch<bulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutResponse>(getBulkUpdateLinesApiCryosCryoYearCooldownLinesFileTypePutUrl(cryo,year,cooldown,fileType),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkLineUpdate,)
  }
);}


/**
 * @summary Create Cooldown
 */
export type createCooldownApiCooldownsNewPostResponse200 = {
  data: CreateResponse
  status: 200
}

export type createCooldownApiCooldownsNewPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createCooldownApiCooldownsNewPostResponseSuccess = (createCooldownApiCooldownsNewPostResponse200) & {
  headers: Headers;
};
export type createCooldownApiCooldownsNewPostResponseError = (createCooldownApiCooldownsNewPostResponse422) & {
  headers: Headers;
};

export type createCooldownApiCooldownsNewPostResponse = (createCooldownApiCooldownsNewPostResponseSuccess | createCooldownApiCooldownsNewPostResponseError)

export const getCreateCooldownApiCooldownsNewPostUrl = () => {


  

  return `/api/cooldowns/new`
}

export const createCooldownApiCooldownsNewPost = async (newCooldownRequest: NewCooldownRequest, options?: RequestInit): Promise<createCooldownApiCooldownsNewPostResponse> => {
  
  return customFetch<createCooldownApiCooldownsNewPostResponse>(getCreateCooldownApiCooldownsNewPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newCooldownRequest,)
  }
);}


/**
 * @summary Add Cooldown
 */
export type addCooldownApiCryosCryoCooldownsNewPostResponse200 = {
  data: CreateResponse
  status: 200
}

export type addCooldownApiCryosCryoCooldownsNewPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type addCooldownApiCryosCryoCooldownsNewPostResponseSuccess = (addCooldownApiCryosCryoCooldownsNewPostResponse200) & {
  headers: Headers;
};
export type addCooldownApiCryosCryoCooldownsNewPostResponseError = (addCooldownApiCryosCryoCooldownsNewPostResponse422) & {
  headers: Headers;
};

export type addCooldownApiCryosCryoCooldownsNewPostResponse = (addCooldownApiCryosCryoCooldownsNewPostResponseSuccess | addCooldownApiCryosCryoCooldownsNewPostResponseError)

export const getAddCooldownApiCryosCryoCooldownsNewPostUrl = (cryo: string,) => {


  

  return `/api/cryos/${cryo}/cooldowns/new`
}

export const addCooldownApiCryosCryoCooldownsNewPost = async (cryo: string,
    newCooldownForCryoRequest: NewCooldownForCryoRequest, options?: RequestInit): Promise<addCooldownApiCryosCryoCooldownsNewPostResponse> => {
  
  return customFetch<addCooldownApiCryosCryoCooldownsNewPostResponse>(getAddCooldownApiCryosCryoCooldownsNewPostUrl(cryo),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newCooldownForCryoRequest,)
  }
);}


/**
 * @summary Update Metadata
 */
export type updateMetadataApiCryosCryoYearCooldownMetadataPatchResponse200 = {
  data: StatusResponse
  status: 200
}

export type updateMetadataApiCryosCryoYearCooldownMetadataPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateMetadataApiCryosCryoYearCooldownMetadataPatchResponseSuccess = (updateMetadataApiCryosCryoYearCooldownMetadataPatchResponse200) & {
  headers: Headers;
};
export type updateMetadataApiCryosCryoYearCooldownMetadataPatchResponseError = (updateMetadataApiCryosCryoYearCooldownMetadataPatchResponse422) & {
  headers: Headers;
};

export type updateMetadataApiCryosCryoYearCooldownMetadataPatchResponse = (updateMetadataApiCryosCryoYearCooldownMetadataPatchResponseSuccess | updateMetadataApiCryosCryoYearCooldownMetadataPatchResponseError)

export const getUpdateMetadataApiCryosCryoYearCooldownMetadataPatchUrl = (cryo: string,
    year: string,
    cooldown: string,) => {


  

  return `/api/cryos/${cryo}/${year}/${cooldown}/metadata`
}

export const updateMetadataApiCryosCryoYearCooldownMetadataPatch = async (cryo: string,
    year: string,
    cooldown: string,
    metadataUpdate: MetadataUpdate, options?: RequestInit): Promise<updateMetadataApiCryosCryoYearCooldownMetadataPatchResponse> => {
  
  return customFetch<updateMetadataApiCryosCryoYearCooldownMetadataPatchResponse>(getUpdateMetadataApiCryosCryoYearCooldownMetadataPatchUrl(cryo,year,cooldown),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      metadataUpdate,)
  }
);}


