/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * cryo-wiring
 * OpenAPI spec version: 0.1.0
 */
import type {
  CooldownDetail,
  CreateResponse,
  CryoEntry,
  HTTPValidationError,
  LineUpdate,
  LinesResponse,
  MetadataUpdate,
  NewCooldownRequest,
  SnapshotRequest,
  SnapshotResponse,
  StatusResponse
} from '../../models';

import { customFetch } from '../../fetcher';

/**
 * @summary List Fridges
 */
export type listFridgesApiFridgesGetResponse200 = {
  data: CryoEntry[]
  status: 200
}
    
export type listFridgesApiFridgesGetResponseSuccess = (listFridgesApiFridgesGetResponse200) & {
  headers: Headers;
};
;

export type listFridgesApiFridgesGetResponse = (listFridgesApiFridgesGetResponseSuccess)

export const getListFridgesApiFridgesGetUrl = () => {


  

  return `/api/fridges`
}

export const listFridgesApiFridgesGet = async ( options?: RequestInit): Promise<listFridgesApiFridgesGetResponse> => {
  
  return customFetch<listFridgesApiFridgesGetResponse>(getListFridgesApiFridgesGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get Cooldown
 */
export type getCooldownApiFridgesFridgeCooldownGetResponse200 = {
  data: CooldownDetail
  status: 200
}

export type getCooldownApiFridgesFridgeCooldownGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getCooldownApiFridgesFridgeCooldownGetResponseSuccess = (getCooldownApiFridgesFridgeCooldownGetResponse200) & {
  headers: Headers;
};
export type getCooldownApiFridgesFridgeCooldownGetResponseError = (getCooldownApiFridgesFridgeCooldownGetResponse422) & {
  headers: Headers;
};

export type getCooldownApiFridgesFridgeCooldownGetResponse = (getCooldownApiFridgesFridgeCooldownGetResponseSuccess | getCooldownApiFridgesFridgeCooldownGetResponseError)

export const getGetCooldownApiFridgesFridgeCooldownGetUrl = (fridge: string,
    cooldown: string,) => {


  

  return `/api/fridges/${fridge}/${cooldown}`
}

export const getCooldownApiFridgesFridgeCooldownGet = async (fridge: string,
    cooldown: string, options?: RequestInit): Promise<getCooldownApiFridgesFridgeCooldownGetResponse> => {
  
  return customFetch<getCooldownApiFridgesFridgeCooldownGetResponse>(getGetCooldownApiFridgesFridgeCooldownGetUrl(fridge,cooldown),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get Diagram
 */
export type getDiagramApiFridgesFridgeCooldownDiagramGetResponse200 = {
  data: unknown
  status: 200
}

export type getDiagramApiFridgesFridgeCooldownDiagramGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getDiagramApiFridgesFridgeCooldownDiagramGetResponseSuccess = (getDiagramApiFridgesFridgeCooldownDiagramGetResponse200) & {
  headers: Headers;
};
export type getDiagramApiFridgesFridgeCooldownDiagramGetResponseError = (getDiagramApiFridgesFridgeCooldownDiagramGetResponse422) & {
  headers: Headers;
};

export type getDiagramApiFridgesFridgeCooldownDiagramGetResponse = (getDiagramApiFridgesFridgeCooldownDiagramGetResponseSuccess | getDiagramApiFridgesFridgeCooldownDiagramGetResponseError)

export const getGetDiagramApiFridgesFridgeCooldownDiagramGetUrl = (fridge: string,
    cooldown: string,) => {


  

  return `/api/fridges/${fridge}/${cooldown}/diagram`
}

export const getDiagramApiFridgesFridgeCooldownDiagramGet = async (fridge: string,
    cooldown: string, options?: RequestInit): Promise<getDiagramApiFridgesFridgeCooldownDiagramGetResponse> => {
  
  return customFetch<getDiagramApiFridgesFridgeCooldownDiagramGetResponse>(getGetDiagramApiFridgesFridgeCooldownDiagramGetUrl(fridge,cooldown),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get Diagram Full
 */
export type getDiagramFullApiFridgesFridgeCooldownDiagramFullGetResponse200 = {
  data: unknown
  status: 200
}

export type getDiagramFullApiFridgesFridgeCooldownDiagramFullGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getDiagramFullApiFridgesFridgeCooldownDiagramFullGetResponseSuccess = (getDiagramFullApiFridgesFridgeCooldownDiagramFullGetResponse200) & {
  headers: Headers;
};
export type getDiagramFullApiFridgesFridgeCooldownDiagramFullGetResponseError = (getDiagramFullApiFridgesFridgeCooldownDiagramFullGetResponse422) & {
  headers: Headers;
};

export type getDiagramFullApiFridgesFridgeCooldownDiagramFullGetResponse = (getDiagramFullApiFridgesFridgeCooldownDiagramFullGetResponseSuccess | getDiagramFullApiFridgesFridgeCooldownDiagramFullGetResponseError)

export const getGetDiagramFullApiFridgesFridgeCooldownDiagramFullGetUrl = (fridge: string,
    cooldown: string,) => {


  

  return `/api/fridges/${fridge}/${cooldown}/diagram/full`
}

export const getDiagramFullApiFridgesFridgeCooldownDiagramFullGet = async (fridge: string,
    cooldown: string, options?: RequestInit): Promise<getDiagramFullApiFridgesFridgeCooldownDiagramFullGetResponse> => {
  
  return customFetch<getDiagramFullApiFridgesFridgeCooldownDiagramFullGetResponse>(getGetDiagramFullApiFridgesFridgeCooldownDiagramFullGetUrl(fridge,cooldown),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get Components
 */
export type getComponentsApiComponentsGetResponse200 = {
  data: unknown
  status: 200
}
    
export type getComponentsApiComponentsGetResponseSuccess = (getComponentsApiComponentsGetResponse200) & {
  headers: Headers;
};
;

export type getComponentsApiComponentsGetResponse = (getComponentsApiComponentsGetResponseSuccess)

export const getGetComponentsApiComponentsGetUrl = () => {


  

  return `/api/components`
}

export const getComponentsApiComponentsGet = async ( options?: RequestInit): Promise<getComponentsApiComponentsGetResponse> => {
  
  return customFetch<getComponentsApiComponentsGetResponse>(getGetComponentsApiComponentsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get Lines
 */
export type getLinesApiFridgesFridgeCooldownLinesGetResponse200 = {
  data: LinesResponse
  status: 200
}

export type getLinesApiFridgesFridgeCooldownLinesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getLinesApiFridgesFridgeCooldownLinesGetResponseSuccess = (getLinesApiFridgesFridgeCooldownLinesGetResponse200) & {
  headers: Headers;
};
export type getLinesApiFridgesFridgeCooldownLinesGetResponseError = (getLinesApiFridgesFridgeCooldownLinesGetResponse422) & {
  headers: Headers;
};

export type getLinesApiFridgesFridgeCooldownLinesGetResponse = (getLinesApiFridgesFridgeCooldownLinesGetResponseSuccess | getLinesApiFridgesFridgeCooldownLinesGetResponseError)

export const getGetLinesApiFridgesFridgeCooldownLinesGetUrl = (fridge: string,
    cooldown: string,) => {


  

  return `/api/fridges/${fridge}/${cooldown}/lines`
}

export const getLinesApiFridgesFridgeCooldownLinesGet = async (fridge: string,
    cooldown: string, options?: RequestInit): Promise<getLinesApiFridgesFridgeCooldownLinesGetResponse> => {
  
  return customFetch<getLinesApiFridgesFridgeCooldownLinesGetResponse>(getGetLinesApiFridgesFridgeCooldownLinesGetUrl(fridge,cooldown),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Update Line
 */
export type updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutResponse200 = {
  data: StatusResponse
  status: 200
}

export type updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutResponseSuccess = (updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutResponse200) & {
  headers: Headers;
};
export type updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutResponseError = (updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutResponse422) & {
  headers: Headers;
};

export type updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutResponse = (updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutResponseSuccess | updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutResponseError)

export const getUpdateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutUrl = (fridge: string,
    cooldown: string,
    fileType: string,
    lineId: string,) => {


  

  return `/api/fridges/${fridge}/${cooldown}/lines/${fileType}/${lineId}`
}

export const updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPut = async (fridge: string,
    cooldown: string,
    fileType: string,
    lineId: string,
    lineUpdate: LineUpdate, options?: RequestInit): Promise<updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutResponse> => {
  
  return customFetch<updateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutResponse>(getUpdateLineApiFridgesFridgeCooldownLinesFileTypeLineIdPutUrl(fridge,cooldown,fileType,lineId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lineUpdate,)
  }
);}


/**
 * @summary Create Cooldown
 */
export type createCooldownApiCooldownsNewPostResponse200 = {
  data: CreateResponse
  status: 200
}

export type createCooldownApiCooldownsNewPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createCooldownApiCooldownsNewPostResponseSuccess = (createCooldownApiCooldownsNewPostResponse200) & {
  headers: Headers;
};
export type createCooldownApiCooldownsNewPostResponseError = (createCooldownApiCooldownsNewPostResponse422) & {
  headers: Headers;
};

export type createCooldownApiCooldownsNewPostResponse = (createCooldownApiCooldownsNewPostResponseSuccess | createCooldownApiCooldownsNewPostResponseError)

export const getCreateCooldownApiCooldownsNewPostUrl = () => {


  

  return `/api/cooldowns/new`
}

export const createCooldownApiCooldownsNewPost = async (newCooldownRequest: NewCooldownRequest, options?: RequestInit): Promise<createCooldownApiCooldownsNewPostResponse> => {
  
  return customFetch<createCooldownApiCooldownsNewPostResponse>(getCreateCooldownApiCooldownsNewPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newCooldownRequest,)
  }
);}


/**
 * @summary Snapshot Cooldown
 */
export type snapshotCooldownApiFridgesFridgeCooldownSnapshotPostResponse200 = {
  data: SnapshotResponse
  status: 200
}

export type snapshotCooldownApiFridgesFridgeCooldownSnapshotPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type snapshotCooldownApiFridgesFridgeCooldownSnapshotPostResponseSuccess = (snapshotCooldownApiFridgesFridgeCooldownSnapshotPostResponse200) & {
  headers: Headers;
};
export type snapshotCooldownApiFridgesFridgeCooldownSnapshotPostResponseError = (snapshotCooldownApiFridgesFridgeCooldownSnapshotPostResponse422) & {
  headers: Headers;
};

export type snapshotCooldownApiFridgesFridgeCooldownSnapshotPostResponse = (snapshotCooldownApiFridgesFridgeCooldownSnapshotPostResponseSuccess | snapshotCooldownApiFridgesFridgeCooldownSnapshotPostResponseError)

export const getSnapshotCooldownApiFridgesFridgeCooldownSnapshotPostUrl = (fridge: string,
    cooldown: string,) => {


  

  return `/api/fridges/${fridge}/${cooldown}/snapshot`
}

export const snapshotCooldownApiFridgesFridgeCooldownSnapshotPost = async (fridge: string,
    cooldown: string,
    snapshotRequest: SnapshotRequest, options?: RequestInit): Promise<snapshotCooldownApiFridgesFridgeCooldownSnapshotPostResponse> => {
  
  return customFetch<snapshotCooldownApiFridgesFridgeCooldownSnapshotPostResponse>(getSnapshotCooldownApiFridgesFridgeCooldownSnapshotPostUrl(fridge,cooldown),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      snapshotRequest,)
  }
);}


/**
 * @summary Update Metadata
 */
export type updateMetadataApiFridgesFridgeCooldownMetadataPatchResponse200 = {
  data: StatusResponse
  status: 200
}

export type updateMetadataApiFridgesFridgeCooldownMetadataPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateMetadataApiFridgesFridgeCooldownMetadataPatchResponseSuccess = (updateMetadataApiFridgesFridgeCooldownMetadataPatchResponse200) & {
  headers: Headers;
};
export type updateMetadataApiFridgesFridgeCooldownMetadataPatchResponseError = (updateMetadataApiFridgesFridgeCooldownMetadataPatchResponse422) & {
  headers: Headers;
};

export type updateMetadataApiFridgesFridgeCooldownMetadataPatchResponse = (updateMetadataApiFridgesFridgeCooldownMetadataPatchResponseSuccess | updateMetadataApiFridgesFridgeCooldownMetadataPatchResponseError)

export const getUpdateMetadataApiFridgesFridgeCooldownMetadataPatchUrl = (fridge: string,
    cooldown: string,) => {


  

  return `/api/fridges/${fridge}/${cooldown}/metadata`
}

export const updateMetadataApiFridgesFridgeCooldownMetadataPatch = async (fridge: string,
    cooldown: string,
    metadataUpdate: MetadataUpdate, options?: RequestInit): Promise<updateMetadataApiFridgesFridgeCooldownMetadataPatchResponse> => {
  
  return customFetch<updateMetadataApiFridgesFridgeCooldownMetadataPatchResponse>(getUpdateMetadataApiFridgesFridgeCooldownMetadataPatchUrl(fridge,cooldown),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      metadataUpdate,)
  }
);}


/**
 * @summary Index
 */
export type indexGetResponse200 = {
  data: string
  status: 200
}
    
export type indexGetResponseSuccess = (indexGetResponse200) & {
  headers: Headers;
};
;

export type indexGetResponse = (indexGetResponseSuccess)

export const getIndexGetUrl = () => {


  

  return `/`
}

export const indexGet = async ( options?: RequestInit): Promise<indexGetResponse> => {
  
  return customFetch<indexGetResponse>(getIndexGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


